#能够编排管理3个容器,php,redis,nginx
version: "3.6"
services: #服务
  nginx:
    image: ubuntu/nginx #指定镜像名称
    container_name: nginx-compose  #容器名称
    ports:  #端口映射
      - "8080:80"
    networks:
      redis-network:
          ipv4_address: 192.168.1.6   #设置ip地址
    stdin_open: true #打开标准输入
    tty: true  #模拟伪终端
    volumes:
      - /home/compose/nginx/conf:/conf
    privileged: true  #特殊权限
    working_dir: /conf #工作目录
  php:
    image: phpdockerio/php72-fpm
    container_name: php-compose
    ports:
      - "9001:9000"
    networks:
      redis-network:
        ipv4_address: 192.168.1.5   #设置ip地址
    working_dir: /www #工作目录
    volumes:
      - /home/compose/php/www:/www
    stdin_open: true  #打开标准输入
    tty: true  #模拟伪终端

  redis:
    image: redis
    container_name: redis-compose
    ports:
      - "6382:6379"
    networks:
       redis-network:
         ipv4_address: 192.168.1.4   #设置ip地址
    working_dir: /usr/src/redis #工作目录
    stdin_open: true
    tty: true
    volumes:
      - /home/compose/redis/master:/usr/src/redis

networks:
  #引用外部预先定义好的网段
  redis-network:
   external:
      name: redis-network
