version: "3.6"
services: #服务
  master-1:
    image: redis-cluster
    container_name: cluster-1
    environment:
      - REALIP=101.200.56.53
      - PORT=6391
      - PORT2=16391
    networks:
       redis-network: #网络名称
         ipv4_address: 192.168.1.20   #设置ip地址
    working_dir: /usr/src/redis #工作目录
    stdin_open: true
    tty: true
    ports:
        - "6391:6379"
        - "16391:16379"
    volumes:
      - /usr/docker/cluster/redis/master-1:/usr/src/redis
    entrypoint:
       - /bin/bash
       - /usr/src/sh/cluster.sh
  master-2:
      image: redis-cluster
      container_name: cluster-2
      environment:
        - REALIP=101.200.56.53
        - PORT=6392
        - PORT2=16392
      networks:
         redis-network: #网络名称
           ipv4_address: 192.168.1.21   #设置ip地址
      working_dir: /usr/src/redis #工作目录
      stdin_open: true
      tty: true
      ports:
          - "6392:6379"
          - "16392:16379"
      volumes:
        - /usr/docker/cluster/redis/master-2:/usr/src/redis
      entrypoint:
         - /bin/bash
         - /usr/src/sh/cluster.sh
  master-3:
      image: redis-cluster
      container_name: cluster-3
      environment:
        - REALIP=101.200.56.53
        - PORT=6393
        - PORT2=16393
      networks:
         redis-network: #网络名称
           ipv4_address: 192.168.1.22   #设置ip地址
      working_dir: /usr/src/redis #工作目录
      stdin_open: true
      tty: true
      ports:
          - "6393:6379"
          - "16393:16379"
      volumes:
        - /usr/docker/cluster/redis/master-3:/usr/src/redis
      entrypoint:
         - /bin/bash
         - /usr/src/sh/cluster.sh
  master-4:
        image: redis-cluster
        container_name: cluster-4
        environment:
          - REALIP=101.200.56.53
          - PORT=6394
          - PORT2=16394
        networks:
           redis-network: #网络名称
             ipv4_address: 192.168.1.23   #设置ip地址
        working_dir: /usr/src/redis #工作目录
        stdin_open: true
        tty: true
        ports:
            - "6394:6379"
            - "16394:16379"
        volumes:
          - /usr/docker/cluster/redis/master-4:/usr/src/redis
        entrypoint:
           - /bin/bash
           - /usr/src/sh/cluster.sh
  slave-1:
        image: redis-cluster
        container_name: cluster-5
        environment:
          - REALIP=101.200.56.53
          - PORT=6395
          - PORT2=16395
        networks:
           redis-network: #网络名称
             ipv4_address: 192.168.1.24   #设置ip地址
        working_dir: /usr/src/redis #工作目录
        stdin_open: true
        tty: true
        ports:
            - "6395:6379"
            - "16395:16379"
        volumes:
          - /usr/docker/cluster/redis/slave-1:/usr/src/redis
        entrypoint:
           - /bin/bash
           - /usr/src/sh/cluster.sh
  slave-2:
        image: redis-cluster
        container_name: cluster-6
        environment:
          - REALIP=101.200.56.53
          - PORT=6396
          - PORT2=16396
        networks:
           redis-network: #网络名称
             ipv4_address: 192.168.1.25   #设置ip地址
        working_dir: /usr/src/redis #工作目录
        stdin_open: true
        tty: true
        ports:
            - "6396:6379"
            - "16396:16379"
        volumes:
          - /usr/docker/cluster/redis/slave-2:/usr/src/redis
        entrypoint:
           - /bin/bash
           - /usr/src/sh/cluster.sh
  slave-3:
      image: redis-cluster
      container_name: cluster-7
      environment:
        - REALIP=101.200.56.53
        - PORT=6397
        - PORT2=16397
      networks:
         redis-network: #网络名称
           ipv4_address: 192.168.1.26   #设置ip地址
      working_dir: /usr/src/redis #工作目录
      stdin_open: true
      tty: true
      ports:
          - "6397:6379"
          - "16397:16379"
      volumes:
        - /usr/docker/cluster/redis/slave-3:/usr/src/redis
      entrypoint:
         - /bin/bash
         - /usr/src/sh/cluster.sh
  slave-4:
        image: redis-cluster
        container_name: cluster-8
        environment:
          - REALIP=101.200.56.53
          - PORT=6398
          - PORT2=16398
        networks:
           redis-network: #网络名称
             ipv4_address: 192.168.1.27   #设置ip地址
        working_dir: /usr/src/redis #工作目录
        stdin_open: true
        tty: true
        ports:
            - "6398:6379"
            - "16398:16379"
        volumes:
          - /usr/docker/cluster/redis/slave-4:/usr/src/redis
        entrypoint:
           - /bin/bash
           - /usr/src/sh/cluster.sh
  #引用外部预先定义好的网段
networks:
  redis-network:
   external:
      name: redis-network
