#能够编排管理3个容器,php,redis,nginx
version: "3.6"
services: #服务
  master-1:
    image: redis
    container_name: master-1
    networks:
       redis-network:
         ipv4_address: 192.168.1.11   #设置ip地址
    working_dir: /usr/src/redis #工作目录
    stdin_open: true
    tty: true
    ports:
        - "6388:6379"
    volumes:
      - /home/sentinel/redis/master-1:/usr/src/redis
    command: ["/usr/local/bin/redis-server","/usr/src/redis/conf/redis.conf"]
  slave-1:
      image: redis
      container_name: slave-1
      links:
        - master-1
      networks:
         redis-network:
           ipv4_address: 192.168.1.12   #设置ip地址
      working_dir: /usr/src/redis #工作目录
      stdin_open: true
      tty: true
      ports:
          - "6389:6379"
      volumes:
        - /home/sentinel/redis/slave-1:/usr/src/redis
      command: ["/usr/local/bin/redis-server","/usr/src/redis/conf/redis.conf"]
  slave-2:
      image: redis
      container_name: slave-2
      links:
        - master-1
      networks:
         redis-network:
           ipv4_address: 192.168.1.13   #设置ip地址
      working_dir: /usr/src/redis #工作目录
      stdin_open: true
      tty: true
      ports:
          - "6390:6379"
      volumes:
        - /home/sentinel/redis/slave-2:/usr/src/redis
      command: ["/usr/local/bin/redis-server","/usr/src/redis/conf/redis.conf"]
  sentinel-1:
      image: redis
      container_name: sentinel-1
      links:
        - master-1
      networks:
         redis-network:
           ipv4_address: 192.168.1.14   #设置ip地址
      working_dir: /usr/src/redis #工作目录
      stdin_open: true
      tty: true
      ports:
          - "26386:26379"
      volumes:
        - /home/sentinel/redis/sentinel-1:/usr/src/redis
      command: ["redis-sentinel", "/usr/src/redis/conf/sentinel.conf"]
  sentinel-2:
      image: redis
      container_name: sentinel-2
      links:
        - master-1
      networks:
         redis-network:
           ipv4_address: 192.168.1.15   #设置ip地址
      working_dir: /usr/src/redis #工作目录
      stdin_open: true
      tty: true
      ports:
          - "26387:26379"
      volumes:
        - /home/sentinel/redis/sentinel-2:/usr/src/redis
      command: ["redis-sentinel", "/usr/src/redis/conf/sentinel.conf"]
  sentinel-3:
      image: redis
      container_name: sentinel-3
      links:
        - master-1
      networks:
         redis-network:
           ipv4_address: 192.168.1.16   #设置ip地址
      working_dir: /usr/src/redis #工作目录
      stdin_open: true
      tty: true
      ports:
          - "26388:26379"
      volumes:
        - /home/sentinel/redis/sentinel-3:/usr/src/redis
      command: ["redis-sentinel", "/usr/src/redis/conf/sentinel.conf"]
#设置网络环境
networks:
  #引用外部预先定义好的网段
  redis-network:
   external:
      name: redis-network
